#!/bin/sh
set -o errexit -o pipefail

for NOTEBOOK in main_genes main_transcripts main_junctions main_exons; do
    cp ../_h/${NOTEBOOK}.ipynb tmp_${NOTEBOOK}.ipynb
    jupyter-nbconvert --execute --ExecutePreprocessor.timeout=-1 \
		      --to notebook --stdout tmp_${NOTEBOOK}.ipynb > ${NOTEBOOK}.ipynb
    jupyter nbconvert --to html ${NOTEBOOK}.ipynb
    jupyter nbconvert --to pdf ${NOTEBOOK}.ipynb
    rm -f tmp_${NOTEBOOK}.ipynb
done

# for NOTEBOOK in main_genes main_exons main_transcripts main_junctions; do
#     cp ../_h/${NOTEBOOK}.ipynb tmp_${NOTEBOOK}.ipynb
# done

# ls ../_h/*ipynb | parallel "jupyter-nbconvert --execute --ExecutePreprocessor.timeout=-1 --to notebook --stdout tmp_{/} > {/}"

# for ii in `pgrep jupyter-nbconvert`; do tail --pid=$ii -f /dev/null;done

# for NOTEBOOK in main_genes main_exons main_transcripts main_junctions; do
#     jupyter nbconvert --to html ${NOTEBOOK}.ipynb
#     jupyter nbconvert --to pdf ${NOTEBOOK}.ipynb
#     rm -f tmp_${NOTEBOOK}.ipynb
# done
