#!/bin/sh
set -o errexit -o pipefail

PHENO="/ceph/projects/v3_phase3_paper/inputs/phenotypes/_m/hippo_phenotypes.csv"
COUNTS="/ceph/users/jbenja13/projects/sex_sz_ria/input/leafcutter/_m"
ANNOT="/ceph/genome/human/gencode26/gtf.ALL/leafcutter_annot/_m"
GTF="/ceph/genome/human/gencode26/gtf.ALL/leafcutter_exons/_m"
SOFTWARE="/ceph/opt/leafcutter"

python ../_h/generate_group_cov.py \
       --pheno_file $PHENO \
       --counts_file $COUNTS/hippocampus_counts.txt.gz

$SOFTWARE/scripts/leafcutter_ds.R --num_threads 10 \
                                  --exon_file=$GTF/gtf_v26_exons.txt.gz \
                                  $COUNTS/hippocampus_counts.txt.gz \
                                  groups_cov_file.txt

$SOFTWARE/leafviz/prepare_results.R --meta_data_file groups_cov_file.txt \
                                    --code leafcutter --FDR 0.05 \
                                    $COUNTS/hippocampus_counts.txt.gz \
                                    leafcutter_ds_cluster_significance.txt \
                                    leafcutter_ds_effect_sizes.txt \
                                    $ANNOT/gencode_v26_hg38
