#!/bin/bash
#$ -cwd
#$ -N subsampling_summary
#$ -o ./summary.log
#$ -e ./summary.log

echo "**** Job starts ****"
date

echo "**** JHPCE info ****"
echo "User: ${USER}"
echo "Job id: ${JOB_ID}"
echo "Job name: ${JOB_NAME}"
echo "Hostname: ${HOSTNAME}"

## List current modules for reproducibility
module list

echo "**** Run general permutation summary ****"

python3 ../_h/summarize_permutation.py

echo "**** Job ends ****"
date
