#!/bin/bash

#chmod +x ../_h/Snakefile #not sure if is necessary

snakemake --printshellcmds --snakefile ../_h/Snakefile --jobs 8


#ls *.genes.annot | awk -F '.' '{print $1}' | sort -u | xargs -I {} sh -c 'mkdir {}; mv {}.* {}'

