#!/bin/bash

THREADS=32
TISSUE="caudate"
ANNOT="/ceph/projects/v4_phase3_paper/inputs/counts/text_files_counts/_m/${TISSUE}"

declare -A MAP_VAR
MAP_VAR["genes"]=gene_annotation.tsv
MAP_VAR["transcripts"]=tx_annotation.tsv
MAP_VAR["exons"]=exon_annotation.tsv
MAP_VAR["junctions"]=jxn_annotation.tsv

for FEATURE in genes transcripts exons junctions; do
    VOOM="../../../differential_expression/${TISSUE}/_m/${FEATURE}/voomSVA.RData"
    python ../_h/dRFE_rf.py --threads $THREADS --feature ${FEATURE} \
           --voom_file ${VOOM} --annot_file $ANNOT/${MAP_VAR[$FEATURE]}
done
