#!/bin/bash

SOFTWARE="/ceph/opt/eigenMT"

Rscript ../_h/prep_genepos.R

seq 1 22 | parallel "Rscript ../_h/prep_eigenMT.R --chrom {}"
Rscript ../_h/prep_eigenMT.R --chrom X

for CHR in `seq 1 22` X; do
    python $SOFTWARE/eigenMT.py \
           --CHROM ${CHR} --cis_dist 0.5e6 \
           --QTL cis.eqtls.${CHR}.txt.gz \
           --GEN genotypes.${CHR}.txt.gz \
           --GENPOS gen.position.${CHR}.txt \
           --PHEPOS phe.position.txt \
           --OUT Brainseq_LIBD.${CHR}.tsv
done

rm *gz *txt
