#!/bin/bash
#$ -cwd
#$ -N subsampling_summary
#$ -o ./summary.log
#$ -e ./summary.log
#$ -m e

echo "**** Job starts ****"
date

echo "**** JHPCE info ****"
echo "User: ${USER}"
echo "Job id: ${JOB_ID}"
echo "Job name: ${JOB_NAME}"
echo "Hostname: ${HOSTNAME}"

## List current modules for reproducibility
module load pandoc
module load tex
module list

echo "**** Run general permutation summary ****"

for NOTEBOOK in main; do
    cp ../_h/${NOTEBOOK}.ipynb tmp_${NOTEBOOK}.ipynb
    jupyter-nbconvert --execute --ExecutePreprocessor.timeout=-1 --to notebook \
		      --stdout tmp_${NOTEBOOK}.ipynb > ${NOTEBOOK}.ipynb
    jupyter nbconvert --to html ${NOTEBOOK}.ipynb
    jupyter nbconvert --to markdown ${NOTEBOOK}.ipynb
    rm -f tmp_${NOTEBOOK}.ipynb
done

echo "**** Job ends ****"
date
